name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # - cron: "*/20 * * * *"
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GIT_USER_EMAIL: "1878302194@qq.com"
      GIT_USER_NAME: "ayou"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Find packages
        shell: bash
        run: |
          # git tag
          chmod +x ./check-version.sh
          ./check-version.sh
      - name: Create and push tags
        shell: bash
        run: |
          chmod +x ./create-push-tags.sh
          ./create-push-tags.sh
